name: Test

on: 
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout  

jobs:
  list_buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: List S3 Buckets
        env: 
          AWS_REGION: ${{ secrets.AWS_REGION }}         
        run: |
            echo "Listing all S3 buckets in region: ${AWS_REGION}"
            aws s3 ls